name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Store Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/test-results

    - name: Store Build Reports
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: app/build/reports

    - name: Store Debug APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/
